# Generated by Django 5.0.6 on 2024-07-28 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comment_comment_body_replay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
